Blogino/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('robots.txt', TemplateView.as_view(
        template_name="robots.txt", content_type="text/plain")),
    path('sitemap.xml', TemplateView.as_view(
        template_name="sitemap.xml", content_type="application/xml")),
]

blog/urls.py
from django.urls import path
from . import views
from django.contrib.auth import  views as auth_views

app_name = 'blog'

urlpatterns = [
    path('', views.home, name='home'),
    path('gallery/', views.GalleryListView.as_view(), name='gallery'),
    path('podcasts/', views.podcast_list, name='podcast_list'),
    path('podcast/<slug>', views.podcast_single, name='podcast_single'),
    path('resume/', views.about, name='about'),
    path('articles/', views.article_list, name='article_all'),
    path('articles/<str:cat>', views.article_list, name='article_list'),
    path('tag/<str:tag>', views.tag_list, name='tag_list'),
    path('article/<slug>', views.article_single, name='article_single'),
    path('search/', views.search, name='search'),
    # path('login/', auth_views.LoginView.as_view(), name='login'),
    # path('logout/', views.log_out, name='logout'),
]

templates/partials/category_list.html
{% load blog_tags %}
<ul>
    {% for category in categories %}
        <li><a href="{% url 'blog:article_list' category.1 %}" class="text-gray-700 dark:text-gray-400"">{{ category.1 }} ({% article_counter category %})</a>
        </li>
    {% endfor %}
</ul>

templates/partials/footer.html
<footer class="bg-gray-200 dark:bg-gray-800 rounded-lg shadow m-4">
  <div class="w-full mx-auto max-w-screen-xl p-4 md:flex md:items-center md:justify-between">
    <span class="text-sm text-gray-500 sm:text-center dark:text-gray-400">© <a href="https://github.com/MohNamdar/Blogino" class="hover:underline">بلاگینو</a> توسط <a class="text-blue-500" href="{% url "blog:about" %}">محمد نامدار</a> کدنویسی شده</span>
    <ul class="flex flex-wrap items-center mt-3 text-sm font-medium text-gray-500 dark:text-gray-400 sm:mt-0">
      <li>
        <a href="{% url 'blog:article_all' %}" class="hover:underline me-4 md:me-6">مقاله ها</a>
      </li>
      <li>
        <a href="{% url 'blog:podcast_list' %}" class="hover:underline me-4 md:me-6">پادکست ها</a>
      </li>
      <li>
        <a href="{% url 'blog:gallery' %}" class="hover:underline me-4 md:me-6">گالری</a>
      </li>
      <li>
        <a href="{% url 'blog:about' %}" class="hover:underline">درباره من</a>
      </li>
    </ul>
  </div>
</footer>

templates/partials/header.html
{% load static %}

{% url 'blog:home' as home_url %}
{% url 'blog:article_all' as article_url %}
{% url 'blog:podcast_list' as podcast_url %}
{% url 'blog:gallery' as gallery_url %}
{% url 'blog:about' as about_url %}

<nav class="bg-white border-gray-200 dark:bg-gray-900">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
    <a href="{% url 'blog:home' %}" class="flex items-center space-x-3 rtl:space-x-reverse">
      <img src="{% static 'images/favicon.png' %}" class="h-8" alt="Logo" />
      <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">بلاگینو</span>
    </a>
    <div class="flex md:order-2">
      <button type="button" data-collapse-toggle="navbar-search" aria-controls="navbar-search" aria-expanded="false" class="md:hidden text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 focus:outline-none focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 rounded-lg text-sm p-2.5 me-1">
        <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z" />
        </svg>
        <span class="sr-only">Search</span>
      </button>
      <div class="relative hidden md:block">
        <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
          <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z" />
          </svg>
          <span class="sr-only">Search icon</span>
        </div>
        <form method="get" action="{% url 'blog:search' %}">
          <input type="text" name="query" required id="search-navbar" class="block w-full p-2 ps-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="جستجو..." />
          <button data-collapse-toggle="navbar-search" type="submit" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-search" aria-expanded="false">
            <span class="sr-only">Open main menu</span>
            <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15" />
            </svg>
          </button>
        </form>
      </div>
    </div>
    <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-search">
      <div class="relative mt-3 md:hidden">
        <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
          <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z" />
          </svg>
        </div>
        <form method="get" action="{% url 'blog:search' %}">
          <input type="text" id="search-navbar" name="query" class="block w-full p-2 ps-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="جستجو..." />
        </form>
      </div>
      <ul class="flex flex-col p-4 md:p-0 mt-4 font-medium border border-gray-100 rounded-lg bg-gray-50 md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
        {% with active='block py-2 px-3 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 md:dark:text-blue-500' inactive='block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700' %}
          <li>
            <a class="{% if request.path == home_url %}
                {{ active }}
              {% else %}
                {{ inactive }}
              {% endif %}"
              aria-current="page"
              href="{% url 'blog:home' %}">
              خانه
            </a>
          </li>
          <li>
            <a class="{% if request.path == article_url %}
                {{ active }}
              {% else %}
                {{ inactive }}
              {% endif %}"
              aria-current="page"
              href="{% url 'blog:article_all' %}">
              مقاله ها
            </a>
          </li>
          <li>
            <a class="{% if request.path == podcast_url %}
                {{ active }}
              {% else %}
                {{ inactive }}
              {% endif %}"
              href="{% url 'blog:podcast_list' %}">
              پادکست ها
            </a>
          </li>
          <li>
            <a class="{% if request.path == about_url %}
                {{ active }}
              {% else %}
                {{ inactive }}
              {% endif %}"
              href="{% url 'blog:about' %}">
              رزومه من
            </a>
          </li>
          <li>
            <a class="{% if request.path == gallery_url %}
                {{ active }}
              {% else %}
                {{ inactive }}
              {% endif %}"
              href="{% url 'blog:gallery' %}">
              گالری
            </a>
          </li>
        {% endwith %}
      </ul>
    </div>
  </div>
</nav>

templates/partials/pagination.html
<section class="flex justify-center mt-4">
  <nav aria-label="Page navigation example">
    <ul class="flex items-center -space-x-px h-10 text-base">
      {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}" class="flex items-center justify-center px-4 h-10 ms-0 leading-tight text-gray-500 bg-white border border-e-0 border-gray-300 rounded-s-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">
          <span class="sr-only">Previous</span>
          <svg class="w-3 h-3 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 1 1 5l4 4" />
          </svg>
        </a>
      {% endif %}

      {% if page_obj.number > 3 %}
        <li>
          <a href="?page=1" class="flex items-center justify-center px-4 h-10 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">1</a>
        </li>
        {% if page_obj.number > 4 %}
          <li>
            <span class="flex items-center justify-center px-4 h-10 leading-tight text-gray-500 bg-white border border-gray-300">...</span>
          </li>
        {% endif %}
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <li>
            <a href="?page={{ num }}" aria-current="page" class="z-10 flex items-center justify-center px-4 h-10 leading-tight text-blue-600 border border-blue-300 bg-blue-50 hover:bg-blue-100 hover:text-blue-700 dark:border-gray-700 dark:bg-gray-700 dark:text-white">{{ num }}</a>
          </li>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <li>
            <a href="?page={{ num }}" class="flex items-center justify-center px-4 h-10 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">{{ num }}</a>
          </li>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        {% if page_obj.number < page_obj.paginator.num_pages|add:'-3' %}
          <li>
            <span class="flex items-center justify-center px-4 h-10 leading-tight text-gray-500 bg-white border border-gray-300">...</span>
          </li>
          <li>
            <a href="?page={{ page_obj.paginator.num_pages }}" class="flex items-center justify-center px-4 h-10 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">{{ page_obj.paginator.num_pages }}</a>
          </li>
        {% elif page_obj.number < page_obj.paginator.num_pages|add:'-2' %}
          <li>
            <a href="?page={{ page_obj.paginator.num_pages }}" class="flex items-center justify-center px-4 h-10 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">{{ page_obj.paginator.num_pages }}</a>
          </li>
        {% endif %}

        <li>
          <a href="?page={{ page_obj.next_page_number }}" class="flex items-center justify-center px-4 h-10 leading-tight text-gray-500 bg-white border border-gray-300 rounded-e-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">
            <span class="sr-only">Next</span>
            <svg class="w-3 h-3 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4" />
            </svg>
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
</section>

templates/partials/sidebar.html
{% load blog_tags %}

<aside>
  <!-- Social media boxes -->
  {% include 'partials/social_link_sidebar.html' %}

  <!-- Categories List -->
  <div class="mt-4 block max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
    <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">دسته‌بندی‌ها</h5>
    {% category_list %}
  </div>

  {% if events %}
    <!-- Today Events Section -->
    <div class="mt-4 block max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
      <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">درچنین روزی:</h5>
      <ul>
        {% for event in events %}
          <li class="text-gray-400">{{ event }}</li>
          <br />
        {% endfor %}
      </ul>
    </div>
  {% endif %}

  <!-- Tags Section -->

  <div class="mt-4 block max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
    <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">برچسب‌ها</h5>
    {% tags_list %}
  </div>
</aside>

templates/partials/social_link_sidebar.html
<div class="w-full max-w-sm p-4 bg-white border border-gray-200 rounded-lg shadow sm:p-6 dark:bg-gray-800 dark:border-gray-700">
  <h5 class="mb-3 text-base font-semibold text-gray-900 md:text-xl dark:text-white">شبکه‌های اجتماعی</h5>
  <ul class="my-4 space-y-3">
    <li>
      <a href="https://www.github.com/MohNamdar" target="_blank" class="flex items-center p-3 text-base font-bold text-gray-900 rounded-lg bg-gray-50 hover:bg-gray-100 group hover:shadow dark:bg-gray-600 dark:hover:bg-gray-500 dark:text-white">
        <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
          <path fill-rule="evenodd" d="M12.006 2a9.847 9.847 0 0 0-6.484 2.44 10.32 10.32 0 0 0-3.393 6.17 10.48 10.48 0 0 0 1.317 6.955 10.045 10.045 0 0 0 5.4 4.418c.504.095.683-.223.683-.494 0-.245-.01-1.052-.014-1.908-2.78.62-3.366-1.21-3.366-1.21a2.711 2.711 0 0 0-1.11-1.5c-.907-.637.07-.621.07-.621.317.044.62.163.885.346.266.183.487.426.647.71.135.253.318.476.538.655a2.079 2.079 0 0 0 2.37.196c.045-.52.27-1.006.635-1.37-2.219-.259-4.554-1.138-4.554-5.07a4.022 4.022 0 0 1 1.031-2.75 3.77 3.77 0 0 1 .096-2.713s.839-.275 2.749 1.05a9.26 9.26 0 0 1 5.004 0c1.906-1.325 2.74-1.05 2.74-1.05.37.858.406 1.828.101 2.713a4.017 4.017 0 0 1 1.029 2.75c0 3.939-2.339 4.805-4.564 5.058a2.471 2.471 0 0 1 .679 1.897c0 1.372-.012 2.477-.012 2.814 0 .272.18.592.687.492a10.05 10.05 0 0 0 5.388-4.421 10.473 10.473 0 0 0 1.313-6.948 10.32 10.32 0 0 0-3.39-6.165A9.847 9.847 0 0 0 12.007 2Z" clip-rule="evenodd" />
        </svg>

        <span class="flex-1 ms-3 whitespace-nowrap">گیت هاب</span>
        <span class="inline-flex items-center justify-center px-2 py-0.5 ms-3 text-xs font-medium text-gray-500 bg-gray-200 rounded dark:bg-gray-700 dark:text-gray-400">+رزومه</span>
      </a>
    </li>
    <li>
      <a href="https://www.instagram.com/MohNamdar" target="_blank" class="flex items-center p-3 text-base font-bold text-gray-900 rounded-lg bg-gray-50 hover:bg-gray-100 group hover:shadow dark:bg-gray-600 dark:hover:bg-gray-500 dark:text-white">
        <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
          <path fill="currentColor" fill-rule="evenodd" d="M3 8a5 5 0 0 1 5-5h8a5 5 0 0 1 5 5v8a5 5 0 0 1-5 5H8a5 5 0 0 1-5-5V8Zm5-3a3 3 0 0 0-3 3v8a3 3 0 0 0 3 3h8a3 3 0 0 0 3-3V8a3 3 0 0 0-3-3H8Zm7.597 2.214a1 1 0 0 1 1-1h.01a1 1 0 1 1 0 2h-.01a1 1 0 0 1-1-1ZM12 9a3 3 0 1 0 0 6 3 3 0 0 0 0-6Zm-5 3a5 5 0 1 1 10 0 5 5 0 0 1-10 0Z" clip-rule="evenodd" />
        </svg>

        <span class="flex-1 ms-3 whitespace-nowrap">اینستاگرام من</span>
      </a>
    </li>
    <li>
      <a href="https://t.me/Codechee" target="_blank" class="flex items-center p-3 text-base font-bold text-gray-900 rounded-lg bg-gray-50 hover:bg-gray-100 group hover:shadow dark:bg-gray-600 dark:hover:bg-gray-500 dark:text-white">
        <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 9H5a1 1 0 0 0-1 1v4a1 1 0 0 0 1 1h6m0-6v6m0-6 5.419-3.87A1 1 0 0 1 18 5.942v12.114a1 1 0 0 1-1.581.814L11 15m7 0a3 3 0 0 0 0-6M6 15h3v5H6v-5Z" />
        </svg>
        <span class="flex-1 ms-3 whitespace-nowrap">کانال تلگرام</span>
      </a>
    </li>
    <li>
      <a href="https://x.com/MohNamdar" target="_blank" class="flex items-center p-3 text-base font-bold text-gray-900 rounded-lg bg-gray-50 hover:bg-gray-100 group hover:shadow dark:bg-gray-600 dark:hover:bg-gray-500 dark:text-white">
        <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
          <path d="M13.795 10.533 20.68 2h-3.073l-5.255 6.517L7.69 2H1l7.806 10.91L1.47 22h3.074l5.705-7.07L15.31 22H22l-8.205-11.467Zm-2.38 2.95L9.97 11.464 4.36 3.627h2.31l4.528 6.317 1.443 2.02 6.018 8.409h-2.31l-4.934-6.89Z" />
        </svg>

        <span class="flex-1 ms-3 whitespace-nowrap">توئیتر من</span>
      </a>
    </li>
  </ul>
</div>

templates/partials/tags_list.html
<ul>
  {% for tag in tags %}
    <li class="inline-block mb-2">
      <a href="{% url 'blog:tag_list' tag.name %}" class="bg-blue-100 text-blue-800 text-sm font-medium me-2 px-2.5 py-0.5 rounded {% cycle 'bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-300' 'bg-gray-100 text-gray-800 dark:bg-gray-700 dark:text-gray-300' 'bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-300' 'bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-300' 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-300' 'bg-indigo-100 text-indigo-800 dark:bg-indigo-900 dark:text-indigo-300' 'bg-purple-100 text-purple-800 dark:bg-purple-900 dark:text-purple-300' 'bg-pink-100 text-pink-800 dark:bg-pink-900 dark:text-pink-300' %}">{{ tag.name }}</a>
    </li>
  {% endfor %}
</ul>