Blogino/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('robots.txt', TemplateView.as_view(
        template_name="robots.txt", content_type="text/plain")),
    path('sitemap.xml', TemplateView.as_view(
        template_name="sitemap.xml", content_type="application/xml")),
]

blog/urls.py
from django.urls import path
from . import views
from django.contrib.auth import  views as auth_views

app_name = 'blog'

urlpatterns = [
    path('', views.home, name='home'),
    path('gallery/', views.GalleryListView.as_view(), name='gallery'),
    path('podcasts/', views.podcast_list, name='podcast_list'),
    path('podcast/<slug>', views.podcast_single, name='podcast_single'),
    path('resume/', views.about, name='about'),
    path('articles/', views.article_list, name='article_all'),
    path('articles/<str:cat>', views.article_list, name='article_list'),
    path('tag/<str:tag>', views.tag_list, name='tag_list'),
    path('article/<slug>', views.article_single, name='article_single'),
    path('search/', views.search, name='search'),
    # path('login/', auth_views.LoginView.as_view(), name='login'),
    # path('logout/', views.log_out, name='logout'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django_jalali.db import models as jmodels
from django.template.defaultfilters import slugify
from django.urls import reverse
from datetime import datetime


# Create your models here.
class User(AbstractUser):
    bio = models.TextField(blank=True, null=True)
    profile = models.ImageField(upload_to="profiles", blank=True, null=True)
    phone = models.CharField(max_length=11, null=True, blank=True)


class Article(models.Model):
    class Category(models.TextChoices):
        AI = 'AI', 'هوش مصنوعی'
        TECHNOLOGY = 'TCH', 'تکنولوژی'
        PROGRAMMING = 'PRG', 'برنامه نویسی'
        SECURITY = 'SEC', 'امنیت'
        DAILY = 'DAY', 'روزانه'

    title = models.CharField(max_length=250)
    cover = models.ImageField(upload_to=f"covers/article/{datetime.now().year}/{datetime.now().month}/", blank=True, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='articles')
    content = models.TextField()
    create_date = jmodels.jDateTimeField(auto_now_add=True)
    update_date = jmodels.jDateTimeField(auto_now=True)
    slug = models.SlugField(max_length=250, unique=True)
    category = models.CharField(choices=Category.choices, max_length=3, default=Category.TECHNOLOGY)
    tags = models.ManyToManyField('Tag', related_name='articles', blank=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-create_date']
        indexes = [models.Index(fields=['-create_date'])]

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("blog:article_single", kwargs={'slug': self.slug})


class Tag(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['name'])
        ]

    def __str__(self):
        return self.name


class Podcast(models.Model):
    class Category(models.TextChoices):
        AI = 'AI', 'هوش مصنوعی'
        TECHNOLOGY = 'TCH', 'تکنولوژی'
        PROGRAMMING = 'PRG', 'برنامه نویسی'
        SECURITY = 'SEC', 'امنیت',
        DAILY = 'DAY', 'روزانه'

    title = models.CharField(max_length=250)
    cover = models.ImageField(upload_to=f"covers/podcast/{datetime.now().year}/{datetime.now().month}/", blank=True, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='podcasts')
    content = models.TextField(blank=True, null=True)
    audio = models.FileField(upload_to=f"podcasts/{datetime.now().year}/{datetime.now().month}/")
    create_date = jmodels.jDateTimeField(auto_now_add=True)
    update_date = jmodels.jDateTimeField(auto_now=True)
    slug = models.SlugField(max_length=250, unique=True)
    category = models.CharField(choices=Category.choices, max_length=3, default=Category.TECHNOLOGY)
    tags = models.ManyToManyField('Tag', related_name='podcasts', blank=True)
    castbox_link = models.URLField(blank=True, null=True)
    google_podcast_link = models.URLField(blank=True, null=True)
    apple_podcast_link = models.URLField(blank=True, null=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-create_date']
        indexes = [models.Index(fields=['-create_date'])]

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("blog:podcast_single", kwargs={'slug': self.slug})


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name="comments", blank=True, null=True)
    podcast = models.ForeignKey(Podcast, on_delete=models.CASCADE, related_name="comments", blank=True, null=True)
    name = models.CharField(max_length=100)
    message = models.TextField()
    email = models.EmailField()
    created = jmodels.jDateTimeField(auto_now_add=True)
    updated = jmodels.jDateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=['-created'])
        ]

    def __str__(self):
        return f"{self.name} #{self.article}"


class Image(models.Model):
    title = models.CharField(max_length=250, null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='images')
    image_file = models.ImageField(upload_to=f"gallery/{datetime.now().year}/{datetime.now().month}/")
    created = jmodels.jDateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=['-created'])
        ]

    def delete(self, *args, **kwargs):
        storage, path = self.image_file.storage, self.image_file.path
        storage.delete(path)
        super().delete(*args, **kwargs)

blog/forms.py
from django import forms
from .models import *


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'message']
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'نام شما', 'class': 'px-0 w-full text-sm text-gray-900 border-0 focus:ring-0 focus:outline-none dark:text-white dark:placeholder-gray-400 dark:bg-gray-800'}),
            'message': forms.Textarea(attrs={'placeholder': 'متن کامنت شما', 'class': 'px-0 w-full text-sm text-gray-900 border-0 focus:ring-0 focus:outline-none dark:text-white dark:placeholder-gray-400 dark:bg-gray-800'}),
            'email': forms.EmailInput(attrs={'placeholder': '(نمایش داده نمیشود) آدرس ایمیل', 'class': 'px-0 w-full text-sm text-gray-900 border-0 focus:ring-0 focus:outline-none dark:text-white dark:placeholder-gray-400 dark:bg-gray-800'}),
        }

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic.list import ListView
from django.contrib.postgres.search import TrigramSimilarity
from blog.forms import *
from blog.models import *
import requests
from datetime import datetime
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout

PAGINATION_PER_PAGE = 6
CATEGORY_MAP = {
    'هوش مصنوعی': 'AI',
    'تکنولوژی': 'TCH',
    'برنامه نویسی': 'PRG',
    'امنیت': 'SEC',
    'روزانه': 'DAY'
}


# Create your views here.
def home(request):
    today = datetime.today()
    url = f'https://holidayapi.ir/gregorian/{today.year}/{today.month}/{today.day}'
    response = requests.get(url)
    data = response.json()
    events = []
    for event in data['events']:
        events.append(event['description'])

    context = {
        'events': events,
    }

    return render(request, 'blog/home.html', context)


class GalleryListView(ListView):
    model = Image
    paginate_by = 10
    template_name = "blog/gallery.html"


def podcast_single(request, slug):
    podcast = get_object_or_404(Podcast, slug=slug)
    comments = podcast.comments.filter(active=True)
    form = CommentForm()
    comment = None
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.podcast = podcast
            comment.save()
    context = {
        'podcast': podcast,
        'comments': comments,
        'form': form,
        'comment': comment
    }
    return render(request, 'blog/podcast_single.html', context)


def podcast_list(request, cat=''):
    if cat:
        category_value = CATEGORY_MAP.get(cat)

        if category_value:
            podcasts = Podcast.objects.filter(category=category_value)
        else:
            return redirect('blog:home')
    else:
        podcasts = Podcast.objects.all()
        cat = 'همه پادکست ها'

    paginator = Paginator(podcasts, PAGINATION_PER_PAGE)
    page_number = request.GET.get('page', 1)
    try:
        page_obj = paginator.page(page_number)
    except PageNotAnInteger:
        raise PageNotAnInteger
    except EmptyPage:
        raise EmptyPage

    context = {
        'page_obj': page_obj,
        'category': cat,
    }

    return render(request, 'blog/podcast_list.html', context)


def about(request):
    return render(request, 'blog/about.html')


def article_single(request, slug):
    article = get_object_or_404(Article, slug=slug)
    comments = article.comments.filter(active=True)
    form = CommentForm()
    comment = None
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.article = article
            comment.save()
    context = {
        'article': article,
        'comments': comments,
        'form': form,
        'comment': comment
    }
    return render(request, 'blog/article_single.html', context)


def article_list(request, cat=''):
    if cat:
        category_value = CATEGORY_MAP.get(cat)

        if category_value:
            articles = Article.objects.filter(category=category_value)
        else:
            return redirect('blog:home')

    else:
        articles = Article.objects.all()
        cat = 'همه مقاله‌ها'

    paginator = Paginator(articles, PAGINATION_PER_PAGE)
    page_number = request.GET.get('page', 1)
    try:
        page_obj = paginator.page(page_number)
    except PageNotAnInteger:
        raise PageNotAnInteger
    except EmptyPage:
        raise EmptyPage

    context = {
        'page_obj': page_obj,
        'category': cat,
    }

    return render(request, 'blog/article_list.html', context)


def tag_list(request, tag):
    tag = get_object_or_404(Tag, name=tag)
    articles = Article.objects.filter(tags=tag)
    paginator = Paginator(articles, PAGINATION_PER_PAGE)
    page_number = request.GET.get('page', 1)
    try:
        page_obj = paginator.page(page_number)
    except PageNotAnInteger:
        raise PageNotAnInteger
    except EmptyPage:
        raise EmptyPage

    context = {
        'page_obj': page_obj,
        'tag': tag
    }

    return render(request, 'blog/tag_list.html', context)


def search(request):
    query = None
    result = []

    if 'query' in request.GET:
        query = request.GET['query']
        result = (Article.objects.annotate(similarity=TrigramSimilarity('title', query))
                  .filter(similarity__gte=0.1).order_by('-similarity'))

    paginator = Paginator(result, PAGINATION_PER_PAGE)
    page_number = request.GET.get('page', 1)
    try:
        page_obj = paginator.page(page_number)
    except PageNotAnInteger:
        raise PageNotAnInteger
    except EmptyPage:
        raise EmptyPage

    context = {
        'query': query,
        'page_obj': page_obj,
    }
    return render(request, 'blog/article_list.html', context)


@login_required
def log_out(request):
    logout(request)
    return redirect('blog:home')

templates/blog/about.html
{% extends 'parent/base.html' %}
{% load static %}

{% block title %}
  رزومه من
{% endblock %}

{% block content %}
  <!-- Breadcrumb -->
  <nav class="flex px-5 py-3 text-gray-700 border border-gray-200 rounded-lg bg-gray-50 dark:bg-gray-800 dark:border-gray-700" aria-label="Breadcrumb">
    <ol class="inline-flex items-center space-x-1 md:space-x-2 rtl:space-x-reverse">
      <li class="inline-flex items-center">
        <a href="{% url 'blog:home' %}" class="inline-flex items-center text-sm font-medium text-gray-700 hover:text-blue-600 dark:text-gray-400 dark:hover:text-white">
          <svg class="w-3 h-3 me-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
            <path d="m19.707 9.293-2-2-7-7a1 1 0 0 0-1.414 0l-7 7-2 2a1 1 0 0 0 1.414 1.414L2 10.414V18a2 2 0 0 0 2 2h3a1 1 0 0 0 1-1v-4a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v4a1 1 0 0 0 1 1h3a2 2 0 0 0 2-2v-7.586l.293.293a1 1 0 0 0 1.414-1.414Z" />
          </svg>خانه
        </a>
      </li>
      <li>
        <div class="flex items-center">
          <svg class="rtl:rotate-180 block w-3 h-3 mx-1 text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4" />
          </svg>
          <span class="ms-1 text-sm font-medium text-gray-700 hover:text-blue-600 md:ms-2 dark:text-gray-400 dark:hover:text-white">رزومه من</span>
        </div>
      </li>
    </ol>
  </nav>

  <!-- Resume -->
  <section>
    <div class="mb-8">
      <a href="{% static 'media/Resume-Dark.pdf' %}" target="_blank" class="hidden dark:inline-block text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">دانلود فایل PDF</a>
      <a href="{% static 'media/Resume-Light.pdf' %}" target="_blank" class="dark:hidden text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">دانلود فایل PDF</a>

      <a href="https://github.com/MohNamdar/Resume" target="_blank" class="text-white bg-gray-800 hover:bg-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700">تمامی نمونه کارها</a>
    </div>

    <img class="w-full hidden dark:block rounded-lg" src="{% static 'images/Resume-Dark.jpg' %}" alt="Resume Dark" />
    <img class="w-full dark:hidden rounded-lg" src="{% static 'images/Resume-Light.jpg' %}" alt="Resume Dark" />
  </section>
{% endblock %}

templates/blog/article_single.html
{% extends 'parent/base.html' %}
{% load jformat %}
{% load blog_tags %}

{% block title %}
  {{ article.title }}
{% endblock %}

{% block content %}
  <!-- Breadcrumb -->
  <nav class="flex px-5 py-3 text-gray-700 border border-gray-200 rounded-lg bg-gray-50 dark:bg-gray-800 dark:border-gray-700" aria-label="Breadcrumb">
    <ol class="inline-flex items-center space-x-1 md:space-x-2 rtl:space-x-reverse">
      <li class="inline-flex items-center">
        <a href="{% url 'blog:home' %}" class="inline-flex items-center text-sm font-medium text-gray-700 hover:text-blue-600 dark:text-gray-400 dark:hover:text-white">
          <svg class="w-3 h-3 me-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
            <path d="m19.707 9.293-2-2-7-7a1 1 0 0 0-1.414 0l-7 7-2 2a1 1 0 0 0 1.414 1.414L2 10.414V18a2 2 0 0 0 2 2h3a1 1 0 0 0 1-1v-4a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v4a1 1 0 0 0 1 1h3a2 2 0 0 0 2-2v-7.586l.293.293a1 1 0 0 0 1.414-1.414Z" />
          </svg>خانه
        </a>
      </li>
      <li>
        <div class="flex items-center">
          <svg class="rtl:rotate-180 block w-3 h-3 mx-1 text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4" />
          </svg>
          <a href="{% url 'blog:article_all' %}" class="ms-1 text-sm font-medium text-gray-500 md:ms-2 dark:text-gray-400">مقاله ها</a>
        </div>
      </li>
      <li aria-current="page">
        <div class="flex items-center">
          <svg class="rtl:rotate-180 w-3 h-3 mx-1 text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4" />
          </svg>
          <a href="{% url 'blog:article_list' article.get_category_display %}" class="ms-1 text-sm font-medium text-gray-500 md:ms-2 dark:text-gray-400">{{ article.get_category_display }}</a>
        </div>
      </li>
    </ol>
  </nav>

  <!-- Article Content -->
  <article class="bg-white py-8 antialiased dark:bg-gray-900 md:py-16">
    <div class="mx-auto max-w-screen-xl px-4 2xl:px-0">
      <div class="mx-auto max-w-5xl">
        <h1 class="text-xl font-semibold text-gray-900 dark:text-white sm:text-2xl">{{ article.title }}</h1>
        <div class="my-8 xl:mb-16 xl:mt-12">
          <img class="w-full rounded-lg" src="{{ article.cover.url }}" alt="{{ article.title }} " />
        </div>
        <div class="mx-auto mb-6 max-w-3xl space-y-6 md:mb-12 text-gray-900 dark:text-white">{{ article.content|markdown }}</div>
      </div>

      <!-- Article Tags -->
      <section>
        <h5 class="text-white">برچسب‌ها:</h5>
        {% tags_list ref=article %}
      </section>

      <!-- Date/Time & Comments Count Info -->
      <div class="mt-4 block w-full p-6 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
        <p class="text-white">تاریخ انتشار: {{ article.create_date|jformat:'%Y/%m/%d' }} | ساعت {{ article.create_date|jformat:'%H:%M' }}</p>
      </div>
    </div>
  </article>

  <!-- Related Articles -->
  <section>
    {% last_articles id=article.id as la %}
    {% if la %}
      <h2 class="text-lg lg:text-2xl font-bold text-gray-900 dark:text-white">آخرین مقاله ها</h2>
      <section class="bg-white dark:bg-gray-900">
        <div class="py-8 px-4 mx-auto max-w-screen-xl lg:py-16 lg:px-6">
          <div class="grid gap-8 lg:grid-cols-2">
            {% for a in la %}
              <article class="p-6 bg-white rounded-lg border border-gray-200 shadow-md dark:bg-gray-800 dark:border-gray-700">
                <h2 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"><a href="{{ a.get_absolute_url }}">{{ a.title }}</a></h2>
                <p class="mb-5 font-light text-gray-500 dark:text-gray-400">{{ a.content|truncatewords:30 }}</p>
                <div class="flex justify-between items-center" dir="ltr">
                  <a href="{{ a.get_absolute_url }}" class="inline-flex items-center font-medium text-gray-500 dark:text-gray-300 hover:underline">
                    <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                      <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 12h14M5 12l4-4m-4 4 4 4" />
                    </svg>بیشتر بخوانید
                  </a>
                </div>
              </article>
            {% endfor %}
          </div>
        </div>
      </section>
    {% endif %}
  </section>

  <!-- Comments Section -->
  <section class="bg-white dark:bg-gray-900 py-8 lg:py-16 antialiased">
    <div class="max-w-2xl mx-auto px-4">
      <div class="flex justify-between items-center mb-6">
        <h2 class="text-lg lg:text-2xl font-bold text-gray-900 dark:text-white">نظرات ({{ comments.count }})</h2>
      </div>

      <form class="mb-6" method="POST" action="#comments">
        {% csrf_token %}
        {% for field in form %}
          <div class="py-2 px-4 mb-4 bg-white rounded-lg rounded-t-lg border border-gray-200 dark:bg-gray-800 dark:border-gray-700">{{ field }}</div>
        {% endfor %}
        <button type="submit" class="inline-flex items-center py-2.5 px-4 text-xs font-medium text-center text-white bg-primary-700 rounded-lg focus:ring-4 focus:ring-primary-200 dark:focus:ring-primary-900 hover:bg-primary-800">ثبت نظر</button>
      </form>
      {% if comment %}
        <div class="toast mt-4" id="comments">
          <div class="p-4 mb-4 text-sm text-green-800 rounded-lg bg-green-50 dark:bg-gray-800 dark:text-green-400" role="alert">کامنت شما ثبت شد</div>
        </div>
      {% endif %}

      <!-- All Comments -->
      {% for comment in comments %}
        <div class="p-6 mb-3 ml-6 lg:ml-12 text-base bg-white rounded-lg dark:bg-gray-800">
          <footer class="flex justify-between items-center mb-2">
            <div class="flex items-center">
              <p class="inline-flex items-center text-sm text-gray-900 dark:text-white font-semibold">{{ comment.name }}</p>
              <p class="text-sm text-gray-600 dark:text-gray-400">
                <span class="mx-4">{{ comment.created|jformat:'%H:%M - %Y/%m/%d' }}</span>
              </p>
            </div>
          </footer>
          <p class="text-gray-500 dark:text-gray-400">{{ comment.message }}</p>
        </div>
      {% endfor %}
    </div>
  </section>
{% endblock %}

templates/blog/gallery.html
{% extends 'parent/base.html' %}
{% load blog_tags %}

{% block title %}
  گالری
{% endblock %}

{% block content %}
  <section class="card">
    <h2 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white text-center mb-8">گالری تصاویر</h2>

    {% if page_obj %}
      <div class="grid grid-cols-2 gap-2">
        {% for image in page_obj %}
          <figure class="relative cursor-pointer">
            <a href="{{ image.image_file.url }}"><img class="rounded-lg" src="{{ image.image_file.url }}" /></a>
            <figcaption class="absolute px-4 text-lg text-white bottom-3">
              {% if image.title %}
                <p>{{ image.title }}</p>
              {% endif %}
              <p>{{ image.created|jalali_date }}</p>
            </figcaption>
          </figure>
        {% endfor %}
      </div>
      {% include 'partials/pagination.html' %}
    {% else %}
      <div class="p-4 my-4 text-sm text-red-800 rounded-lg bg-red-50 dark:bg-gray-800 dark:text-red-400" role="alert">
        <span class="font-medium">متاسفم هیچ تصویری پیدا نشد :(</span>
      </div>
    {% endif %}
  </section>
{% endblock %}

templates/blog/home.html
m {% extends 'parent/base.html' %}
{% load static %}
{% load jformat %}
{% load blog_tags %}
{% block title %}
  وبسایت شخصی
{% endblock %}

{% block content %}
  <section dir="ltr" class="bg-white dark:bg-gray-900">
    <div class="gap-8 items-center py-8 px-4 mx-auto max-w-screen-xl xl:gap-16 md:grid md:grid-cols-2 sm:py-16 lg:px-6">
      <img class="w-full" src="{% static 'media\laptop-animation.gif' %}" alt="dashboard image" />
      <div class="mt-4 md:mt-0">
        <h2 class="mb-4 text-4xl tracking-tight font-extrabold text-gray-900 dark:text-white text-right">👋 محمد نامدار هستم</h2>
        <p class="mb-6 font-light text-gray-500 md:text-lg dark:text-gray-400 text-right">مقاله ها و پادکست هایی که منتشر میکنم رو توی همین وبسایت آپلود میکنم</p>
        <div class="flex flex-col space-y-4 sm:flex-row sm:space-y-0 sm:space-x-4">
          <a href="{% url 'blog:about' %}" class="inline-flex items-center justify-center px-4 py-2.5 text-base font-medium text-center text-gray-900 border border-gray-300 rounded-lg hover:bg-gray-100 focus:ring-4 focus:ring-gray-100 dark:text-white dark:border-gray-600 dark:hover:bg-gray-700 dark:focus:ring-gray-600">
            <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 12h14M5 12l4-4m-4 4 4 4" />
            </svg>مشاهده روزمه
          </a>
          <a href="{% url 'blog:article_all' %}" class="inline-flex items-center justify-center px-4 py-2.5 text-base font-medium text-center text-white bg-primary-700 rounded-lg hover:bg-primary-800 focus:ring-4 focus:ring-primary-300 dark:focus:ring-primary-900">مشاهده مقالات</a>
        </div>
      </div>
    </div>
  </section>
{% endblock %}